# Generated by Django 5.1.1 on 2024-09-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='file',
            new_name='audio_file',
        ),
    ]
