# Generated by Django 5.1.1 on 2024-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_rename_file_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='start_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
